accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include(('accounts.urls','accounts'),namespace='accounts')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from venv import create
from django.urls import path
from . import views


urlpatterns = [
    path('' , views.base , name='base'),
    path('<int:id>/',views.detail,name='detail'),
    path('create',views.create, name='create'),
    path('edit/<int:id>/',views.edit, name='edit'),
    path('delete/<int:id>/',views.delete, name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=1000)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    Image=models.ImageField(null=True,blank=True,upload_to="images/")

main/forms.py
from .models import Post
from django.forms import ModelForm


class postform(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'invalid credentials')
            return redirect('/accounts/login')
    else:
        return render(request, 'accounts/login.html')



def register(request):
    if request.method == 'POST':
        name = request.POST['name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'username exists')
                return redirect('/accounts/register')
            else:
                user = User.objects.create_user(first_name=name, username=username, email=email, password=password1)
                user.save()
                return redirect('/accounts/login')
        else:
            messages.info(request, 'password did not match')
            return redirect('/accounts/register')
    return render(request, 'accounts/register.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

main/views.py
from turtle import pos
from django.shortcuts import redirect, render
from .models import Post
from .forms import postform
from django.contrib.auth import get_user
# Create your views here.


def base(request):
    allblog=Post.objects.all()
    return render(request, 'main/index.html',{'allblog':allblog})

def detail(request,id):
    blog=Post.objects.get(id=id)
    return render(request, 'main/detail.html',{'blog':blog})

def create(request):
    form = postform
    if request.method == "POST":
        form = postform(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        
        user = get_user(request)
        form = postform(initial={'author': user})


    return render(request, 'main/create.html', {'form': form})

def edit(request, id):
    ob = Post.objects.get(id=id)
    form = postform(instance=ob)
    if request.method == "POST":
        form = postform(request.POST, instance=ob)
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'main/create.html', {'form': form})


def delete(request, id):
    ob = Post.objects.get(id=id)
    ob.delete()
    allblog = Post.objects.all()
    return render(request, 'main/index.html', {'allblog': allblog})

templates/accounts/login.html
{% extends "main/base.html" %}

{% block content %}
  

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
    <style>
        .gradient-custom {
            /* fallback for old browsers */
            background: #d6cbd6;
            
            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right, rgb(136, 136, 159), rgba(37, 117, 252, 1));
            
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, rgb(190, 182, 199), rgba(37, 117, 252, 1))
            }
    </style>
</head>
<body>
  <form action="login" method="post">
    {% csrf_token %}
  <div class="container">
    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
    
                <div class="mb-md-5 mt-md-4 pb-5">
    
                  <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5">Please enter your login and password!</p>
    
                  <div class="form-outline form-white mb-4">
                    <input type="text" name ="username" id="typeEmailX" class="form-control form-control-lg" />
                    <label class="form-label" for="typeEmailX">Username</label>
                  </div>
    
                  <div class="form-outline form-white mb-4">
                    <input type="password" name ="password" id="typePasswordX" class="form-control form-control-lg" />
                    <label class="form-label" for="typePasswordX">Password</label>
                  </div>
    
                  <!--<p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>-->
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
    
                  <div class="d-flex justify-content-center text-center mt-4 pt-1">
                    {% for message in messages %}
                      <h1>{{message}}</h1>
                    {% endfor %}
                    <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                  </div>
    
                </div>
    
                <div>
                  <p class="mb-0">Don't have an account? <a href="{% url 'accounts:register'%}" class="text-white-50 fw-bold">Sign Up</a>
                  </p>
                </div>
    
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </form>
</body>
</html>
{% endblock content %}

templates/accounts/register.html
{% extends "main/base.html" %}

{% block content %}
  

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
    <style>
        .gradient-custom {
            /* fallback for old browsers */
            background: #d6cbd6;
            
            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right, rgb(136, 136, 159), rgb(37, 117, 252));
            
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, rgb(190, 182, 199), rgba(37, 117, 252, 1))
            }
    </style>
</head>
<body>
  <form action="register" method="post">
    {% csrf_token %}
  <div class="container">
    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
    
                <div class="mb-md-5 mt-md-4 pb-5">
    
                  <h2 class="fw-bold mb-2 text-uppercase">Register</h2>
                  <p class="text-white-50 mb-5"> Enter your information</p>

                  <div class="form-outline form-white mb-4">
                    <input type="username" name ="name" id="typePasswordX" class="form-control form-control-lg" />
                    <label class="form-label" for="typePasswordX">Name</label>
                  </div>
    
                  <div class="form-outline form-white mb-4">
                    <input type="text" name ="username" id="typeEmailX" class="form-control form-control-lg" />
                    <label class="form-label" for="typeEmailX">Username</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="email" name ="email" id="typePasswordX" class="form-control form-control-lg" />
                    <label class="form-label" for="typePasswordX">Email</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" name ="password1" id="" class="form-control form-control-lg" />
                    <label class="form-label" for="">Password</label>
                  </div>
    
                  <div class="form-outline form-white mb-4">
                    <input type="password" name ="password2" id="" class="form-control form-control-lg" />
                    <label class="form-label" for="">Enter Password again</label>
                  </div>
    
                  <!--<p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>-->
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Register</button>
    
                  <div class="d-flex justify-content-center text-center mt-4 pt-1">
                    {% for message in messages %}
                        <h1>{{message}}</h1>
                    {% endfor %}
                    <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                  </div>
    
                </div>
    
                <div>
                  <p class="mb-0">Already Have an account?: <a href="{% url 'accounts:login'%}" class="text-white-50 fw-bold">Login</a>
                  </p>
                </div>
    
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </form>
</body>
</html>
{% endblock content %}

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <title>Document</title> 
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
        <div class="container">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'base' %}"><h3>Hello {{request.user}}</h3><span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                      
                      {% if user.is_authenticated %}
      
                      <a class="nav-link" href="{% url 'accounts:logout' %}"><h3>Logout</h3></a>
                        
                      {% else %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}"><h3>Login</h3></a>
                      </li>
                        
                      
                      <a class="nav-link" href="{% url 'accounts:register' %}"><h3>Register</h3></a>

                      {% endif %}
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'create' %}"><h3>Add Blogs</h3></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:login' %}"><h3>Add Blogs</h3></a>
                    </li>



                    {% endif %}
                    
                  </ul>
                </div>
              </nav>

        </div>
    </div>



    
 
    {% block content %}
      
    {% endblock content %}
</body>
</html>

templates/main/create.html
{% extends 'main/base.html'%}
{% block content %}
<h1>Create a new Blog</h1>
<form method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}
       {{ form.media }}
        <input type="submit" value="Submit">

</form>  


{% endblock content %}

templates/main/detail.html
{% extends "main/base.html" %}
{% block content %}
  

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</head>
<body>
    
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <img src="{{ blog.Image.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 30px;">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        {{ blog.title }}

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {{ blog.author }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {{ blog.content }}

                    </div>

                </div>
                

            </div>


        </div>

    </div>
    


</body>
</html>
{% endblock content %}

templates/main/index.html
{% extends 'main/base.html' %}

{% block content%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</head>
<body>
    
    <!--<table>              
        <tr>
            <th><h1>Blogs</h1></th>
            
        </tr>   
        {% for blog in allblog %}
        <tr>
             
            <td><img src="{{ blog.Image.url }}" class="img-responsive" style="width: 25%; float: left; margin-right: 10px;" /></td>
               
        </tr>
        <tr>
            <td><h2>{{blog.title}}</h2> <h3>By</h3> <h2>{{blog.author}}</h2></td>
            
            
        </tr>
        <tr><td><h3><a href="{{blog.id}}">Read more</a></h3></td></tr>
        
        {% endfor %}
    </table>-->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form class="card card-sm">
                    <div class="card-body row no-gutters align-item-center">
                        

                    </div>

                </form>
            </div>

        </div>

            
    </div>
   
            

                {% for blog in allblog %}
                <div class="col-md-3">
                    <div class="card">
                        <img src="{{ blog.Image.url }}" class="img-responsive" style="width: 60%; float: left; margin-right: 10px;" />
                        <div class="card-body">
                            <div  class="card-title">{{blog.title}}</div>
                            <div class="card-text"><h3>By</h3> <h2>{{blog.author}}</div>
                            <a href="{{blog.id}}" class="btn btn-warning">Read more</a>
                            
                            {% if user.is_authenticated %}
                                
                                {% if user.id == blog.author.id %}
                                    
                                
                                    
                            <a href="{% url 'edit' blog.id %}" class="btn btn-warning">Edit</a>
                            <a href="{% url 'delete' blog.id %}"  class="btn btn-warning">Delete</a>
                                {% endif %}
                                
                            {% endif %}
                                
                            </div>
                    </div>

                </div>
                {% endfor %}


                </div>
</body>
</html>
{% endblock content %}